using System;
using Newtonsoft.Json.Linq;
using Snapper.Exceptions;

namespace Snapper.Json
{
    internal class JsonSnapshotSanitiser
    {
        public object SanitiseSnapshot(object snapshot)
        {
            try
            {
                if (snapshot is string stringSnapshot)
                {
                    if (StringIsJsonObject(stringSnapshot))
                    {
                        try
                        {
                            return JObject.Parse(stringSnapshot);
                        }
                        catch (Exception e)
                        {
                            throw new MalformedJsonSnapshotException(e);
                        }
                    }
                }

                JObject.FromObject(snapshot);
                return snapshot;
            }
            catch (ArgumentException)
            {
                return new { AutoGenerated = snapshot };
            }
        }

        private static bool StringIsJsonObject(string stringSnapshot)
        {
            var trimmedString = stringSnapshot.Trim();
            return trimmedString.StartsWith("{") && trimmedString.EndsWith("}");
        }
    }
}
